### ISSUE TITLE
Lage ei liste med alt av funksjoner vi må skrive

### ISSUE THREAD

**Issue by IngebrigtSR** [IngebrigtSR/HeisprosjektMaster#2]

**Comment by JayKays** [comment]
FSM:
UpdateLights funksjon som tar inn hele logen
Egen funksjon for FloorArrival ?
En ordentlig initFSM funksjon som kjører heisen ned til en etasje, sopper og oppadaterer state osv.
Fikse FSM til å oppdatere state, osv på heisen

Generelt opdatere funksjonene til å ta inn en Elevator og ikke separate parametre (kan være mer oversiklig)

**Comment by JayKays** [comment]
Network:
Finne ut en smart måte heisene vet hvilken index de har i loggen

Pakke/unpakke log til å broadcaste

**Comment by JayKays** [comment]
Main:

Skriv main funksjonen, tenker kanskje en select er smart. Med channels for å motta log, sende log, motta ting fra FSM som skal broadcastes,

**Comment by JayKays** [comment]
config:

Legge til ting som passer å ha her  når de dukker opp
